[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/treino/service-worker.js"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"