[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/treino/manifest.json"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"